/*
* Copyright 2013 JUGChennai
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package in.jugchennai.forge.android;

/**
 * 
 * <b>Contributors</b>
 * 
 * @author Rajmahendra Hegde <rajmahendra@gmail.com>
 * @author Arivazhagan Ambigapathi <arivu86@gmail.com>
 *
 */

import static junit.framework.Assert.assertNotNull;
import static junit.framework.Assert.assertTrue;

import java.io.File;

import javax.inject.Inject;

import junit.framework.Assert;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.forge.parser.xml.Node;
import org.jboss.forge.parser.xml.XMLParser;
import org.jboss.forge.project.Project;
import org.jboss.forge.project.dependencies.DependencyResolver;
import org.jboss.forge.project.facets.ResourceFacet;
import org.jboss.forge.resources.DirectoryResource;
import org.jboss.forge.resources.FileResource;
import org.jboss.forge.test.AbstractShellTest;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.junit.Before;
import org.junit.Test;

public class AndroidPluginTest extends AbstractShellTest {
	  @Inject
	    private DependencyResolver resolver;
	  	String [][] value_cmds = {{"string_add","color_add","dimens_add"},{"android string-add --name test --value testvalue",
	  		"android color-add --name test --hexvalue #ccfff","android dimens-add --name test --pixel 50dp"}};
	  	

	    @Deployment
	    public static JavaArchive getDeployment() {
	        return AbstractShellTest.getDeployment().addPackages(true, AndroidPlugin.class.getPackage());
	    }

	    private Project initializeAndriodFacesProject() throws Exception {
	        Project p = initializeJavaProject();
	        getShell().execute("android setup");
	        return p;
	    }

	    @Test
	    public void Setup() throws Exception {
	    	initializeAndriodFacesProject();
	        final Project project = initializeAndriodFacesProject();
	        assertNotNull(resolver);
	        assertNotNull(project.hasFacet(AndroidFacet.class));

	    }
	    
	    /*
	     * Check is all the values xml files is generated by "andriod setup"
	     * */
	    @Test
	    public void isvalueFolderInRes() throws Exception {
	    	final Project project = initializeAndriodFacesProject();
	    	DirectoryResource projectRoot = project.getProjectRoot();
	    	DirectoryResource resDirectory = projectRoot.getOrCreateChildDirectory("res");
	    	DirectoryResource valuesDirectory = resDirectory.getOrCreateChildDirectory("values");
	        assertTrue(valuesDirectory.getChild("strings.xml").exists());
	        assertTrue(valuesDirectory.getChild("color.xml").exists());
	        assertTrue(valuesDirectory.getChild("dimens.xml").exists());
	    }
	    
	    /*
	     * value_parser is used to test the add commands for string,color and dimens.
	     * If the name "test" exist the test case is passing
	     */
	    public void values_TestBot (String _uri,String _cmd) throws Exception{
	    	final Project project = initializeAndriodFacesProject();
	    	FileResource<?> tempFile = project.getProjectRoot().getChildOfType(FileResource.class, _uri);
	    	getShell().execute(_cmd);
	        if(tempFile.exists()) {
		        Node node = XMLParser.parse(tempFile.getResourceInputStream());
	    		Node noderes = node.getOrCreate("resources");
	    			for(Node tempres : noderes.getChildren()){
	    				if(tempres.getAttribute("name").equals("test"))
	    				{
	    					Assert.assertEquals(tempres.getAttribute("name"), "test");
	    				}
	    		}
		    }
	    }
	    
	    /*
	     * value_cmd test all the commands that related to value resources
	     */
	    @Test
	    public void values_cmd() throws Exception {
	    	values_TestBot ("res/values/strings.xml","android string-add --name test --value testvalue");
	    	values_TestBot ("res/values/color.xml","android color-add --name test2 --hexvalue #ccfff");
	    	values_TestBot ("res/values/color.xml","android dimens-add --name test --pixel 50dp");
	    }
	    
}